<?php

namespace PlanIt\BudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InflowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InflowRepository extends EntityRepository
{
}
