<?php

namespace PlanIt\BudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeExpenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeExpenseRepository extends EntityRepository
{
}
