PlanItGuestsBundle_guest_create:
    pattern:  /module/{module_id}/guests/create
    defaults: { _controller: PlanItGuestsBundle:Guest:create }
    requirements:
        _method:  POST
        blog_id: \d+