plan_it_rest:
    resource: "@PlanItRestBundle/Resources/config/routing.yml"
    prefix:   /

plan_it_user:
    resource: "@PlanItUserBundle/Resources/config/routing.yml"
    prefix:   /

#REST 
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api