PlanItModuleBundle_module:
    path:     /event/{event_id}/module/{module_id}
    defaults: { _controller: PlanItModuleBundle:Page:module}
    requirements:
        _method:  GET
        event_id: \d+
        module_id: \d+