<?php

namespace PlanIt\ModuleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
    public function findBySlug($event_id, $slug)
    {
        $qb = $this->createQueryBuilder('m')
                   ->select('m')
                   ->where('m.event = :event_id')
                   ->addOrderBy('m.begin_date')
                   ->setParameter('user_id', $user_id);
                   ->andWhere('m.slug = :slug')
                   ->setParameter('slug', $slug);
        //Ajouter vérificaiton pour afficher que les évenments à venir pas les terminés

        return $qb->getQuery()
                  ->getResult();
    }
}