<?php

namespace PlanIt\PlaceBundle\Repository;

use Doctrine\ORM\EntityRepository;
use PlanIt\PlaceBundle\Entity\Place;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{
	public function findByModule($module_id){
        return $this->createQueryBuilder('p')
                    ->leftjoin('p.module', 'm')
                    ->where('m.id = :module_id')
                    ->setParameter('module_id', $module_id)
                    ->getQuery()
                    ->getResult();
	}
}
