<?php

namespace PlanIt\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findByUser($user_id)
    {
        $qb = $this->createQueryBuilder('e')
                   ->select('e')
                   ->where('e.user = :user_id')
                   ->addOrderBy('e.begin_date')
                   ->setParameter('user_id', $user_id);
        //Ajouter vérificaiton pour afficher que les évenments à venir pas les terminés

        return $qb->getQuery()
                  ->getResult();
    }
}