PlanItEventBundle_event:
    path:     /event/{id}
    defaults: { _controller: PlanItEventBundle:Page:event }
    requirements:
        _method:  GET
        id: \d+
PlanItEventBundle_form:
    path:     /event/form
    defaults: { _controller: PlanItEventBundle:Page:form }
    requirements:
        _method:  GET