<?php

namespace PlanIt\GuestsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GuestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestRepository extends EntityRepository
{
    public function getGuestsforModule($module_id)
    {
        $qb = $this->createQueryBuilder('g')
                   ->select('g')
                   ->where('g.event = :module_id')
                   ->setParameter('module_id', $module_id);

        return $qb->getQuery()
                  ->getResult();
    }
    

}