<?php

namespace PlanIt\GuestsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GuestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestRepository extends EntityRepository
{
	public function countGuests($event_id){
		$guests = $this->createQueryBuilder('g')
                    ->join('g.module', 'm')
                    ->join('m.event', 'e')
                    ->where('e.id = :event_id')
                    ->andWhere('g.confirmed = 1')
                    ->setParameter('event_id', $event_id)
                    ->getQuery()
                    ->getResult();

        return count($guests);

	}
}
