<?php

namespace PlanIt\GuestsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GuestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentMeansRepository extends EntityRepository
{
	// public function getPaymentsforModule($module_id)
 //    {

 //      return $this->createQueryBuilder('p')
	// 	        ->where($er->createQueryBuilder('p')->expr()->notIn('p.id', ':ids'))
	// 	        ->setParameter('ids', $er->createQueryBuilder('pp')
	// 	        ->select('pp.id')
	// 	        ->leftjoin('pp.modules', 'm')
	// 	        ->where('m.id = :module_id')
	// 	        ->setParameter('module_id', $module->getId())
	// 	        ->getQuery()
	// 	        ->getResult()
	// 	        , \Doctrine\DBAL\Connection::PARAM_INT_ARRAY);
 //    }
}