<?php

namespace PlanIt\GuestsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use PlanIt\GuestsBundle\Entity\PaymentMeans;

/**
 * PaymentMeansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentMeansRepository extends EntityRepository
{
	public function findByGuestsModule($id){
          $module_payments = $this->createQueryBuilder('pp')
                  ->leftjoin('pp.modules', 'm')
                  ->where('m.id = :module_id')
                  ->setParameter('module_id', $id)
                  ->getQuery()
                  ->getResult();

          if(empty($module_payments)){
               return $this->createQueryBuilder('pp')
                            ->getQuery()
                            ->getResult();
          }else{
               return $this->createQueryBuilder('p')
                    ->where($this->createQueryBuilder('p')->expr()->notIn('p.id', ':ids'))
                    ->setParameter('ids', $this->createQueryBuilder('pp')
                    ->select('pp.id')
                    ->leftjoin('pp.modules', 'm')
                    ->where('m.id = :module_id')
                    ->setParameter('module_id', $id)
                    ->getQuery()
                    ->getResult()
                    , \Doctrine\DBAL\Connection::PARAM_INT_ARRAY)
                    ->getQuery()
                    ->getResult();
          }
	}
}
