PlanItUserBundle_homepage:
    path:     /home/{id}
    defaults: { _controller: PlanItUserBundle:Page:index }
    requirements:
        _method:  GET
        id: \d+
PlanItUserBundle_login:
    path:     /login
    defaults: { _controller: PlanItUserBundle:Page:login }
    requirements:
        _method:  GET
        id: \d+
PlanItUserBundle_register:
    path:     /register
    defaults: { _controller: PlanItUserBundle:Page:register }
    requirements:
        _method:  GET
        id: \d+
PlanItUserBundle_logout:
    path:     /logout
    defaults: { _controller: PlanItUserBundle:Page:logout }
    requirements:
        _method:  GET
        id: \d+