PlanItUserBundle_homepage:
    path:     /home/{id}
    defaults: { _controller: PlanItUserBundle:Page:index }
    requirements:
        _method:  GET
        id: \d+

PlanItUserBundle_eventpage:
    path:     /event/{id}
    defaults: { _controller: PlanItUserBundle:Page:event }
    requirements:
        _method:  GET
        id: \d+