<?php

namespace PlanIt\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findByEmail($email)
    {
        $qb = $this->createQueryBuilder('u')
                   ->select('u')
                   ->where('u.email = :email')
                   ->setParameter('email', $email);

        return $qb->getQuery()
                  ->getResult();
    }
}