users : 
  type: rest
  resource:     "PlanItRestBundle:UserRest"
  name_prefix:  api_

events : 
  type: rest
  resource:     "PlanItRestBundle:EventRest"
  name_prefix:  api_

modules : 
  type: rest
  resource:     "PlanItRestBundle:ModuleRest"
  name_prefix:  api_

guests : 
  type: rest
  resource:     "PlanItRestBundle:GuestRest"
  name_prefix:  api_

typeguest : 
  type: rest
  resource:     "PlanItRestBundle:TypeGuestRest"
  name_prefix:  api_

guests_module : 
  type: rest
  resource:     "PlanItRestBundle:GuestsModuleRest"
  name_prefix:  api_

budget_module : 
  type: rest
  resource:     "PlanItRestBundle:BudgetModuleRest"
  name_prefix:  api_

place_module : 
  type: rest
  resource:     "PlanItRestBundle:PlaceModuleRest"
  name_prefix:  api_

transportation_module : 
  type: rest
  resource:     "PlanItRestBundle:TransportationModuleRest"
  name_prefix:  api_

todo_module : 
  type: rest
  resource:     "PlanItRestBundle:TodoModuleRest"
  name_prefix:  api_