users : 
  type: rest
  resource:     "PlanItRestBundle:UserRest"
  name_prefix:  api_

events : 
  type: rest
  resource:     "PlanItRestBundle:EventRest"
  name_prefix:  api_

modules : 
  type: rest
  resource:     "PlanItRestBundle:ModuleRest"
  name_prefix:  api_

guests : 
  type: rest
  resource:     "PlanItRestBundle:GuestRest"
  name_prefix:  api_